#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#include QMK_KEYBOARD_CONFIG_H

#undef TAPPING_TERM
#define TAPPING_TERM 230


#define NO_ACTION_FUNCTION
#define NO_ACTION_MACRO
#define NO_ACTION_ONESHOT

// #define ENABLE_STABLE_LAYER

#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD

#endif
