#include "youhei.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[L_BASE] = KEYMAP(
		// left hand
		CLEAR, KC_4, KC_3, KC_2, KC_1, KC_5, KC_NO,
		KC_NO, KC_Z, KC_U, KC_O, KC_P, KC_J, KC_BSLS,
		KC_QUOT, LCTL_T(KC_W), LALT_T(KC_A), LGUI_T(KC_E), DIR_T(KC_I), KC_Y,
		KC_LALT, KC_SLSH, KC_COMM, KC_DOT, KC_B, KC_MINS, KC_INS,
		KC_LCTL, KC_LGUI, KC_RCLK, KC_MCLK, KC_LCLK,
		// thumb
		KC_ESC, KC_MULTI,
		KC_HENK,
		KC_ENT, OS_SFT, KC_CAPS,
		// right hand
		KC_NO, KC_8, KC_9, KC_0, KC_6, KC_7, KC_PAUS,
		KC_EQL, KC_V, KC_M, KC_L, KC_C, KC_X, KC_NO,
		KC_H, FN_T(KC_R), RGUI_T(KC_T), ALT_T(KC_S), RCTL_T(KC_F), KC_SCLN,
		KC_GRV, KC_K, KC_N, KC_G, KC_D, KC_Q, KC_LALT,
		KC_LBRC, KC_RBRC, KC_KANA, KC_RGUI, KC_RCTL,
		// thumb
		KC_MHEN, KC_TAB,
		KC_BSPC,
		KC_DEL, OS_SFT, KC_SPC
	),
	[L_DIRECTION] = KEYMAP(
		// left hand
		CLEAR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		// thumb
		KC_TRNS, KC_TRNS,
		KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		// right hand
		KC_NO, KC_F8, KC_F9, KC_F10, KC_F6, KC_F7, KC_NO,
		KC_NO, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_NO, KC_NO,
		KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_APP, KC_SLCK,
		KC_NO, KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R, KC_NO, KC_NO,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		// thumb
		KC_TRNS, KC_TRNS,
		KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS
	),
	[L_FUNCTION] = KEYMAP(
		// left hand
		CLEAR, KC_F4, KC_F3, KC_F2, KC_F1, KC_F5, KC_NO,
		KC_NO, KC_F11, KC_F12, KC_NO, KC_PSCR, KC_NO, KC_NO,
		KC_NO, KC_NO, KC_VOLD, KC_VOLU, KC_MUTE, KC_NO,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		// thumb
		KC_TRNS, KC_TRNS,
		KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		// right hand
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RESET,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		// thumb
		KC_TRNS, KC_TRNS,
		KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS
	),
};
