SUBPROJECT_DEFAULT = ez

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
CUSTOM_MATRIX = yes
SLEEP_LED_ENABLE = no
NKRO_ENABLE = yes
MIDI_ENABLE = no
UNICODE_ENABLE = no
ONEHAND_ENABLE = no
RGBLIGHT_ENABLE = no
API_SYSEX_ENABLE = no

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
