#pragma once

#include "quantum_keycodes.h"

enum Layer {
	L_BASE,
#ifdef ENABLE_STABLE_LAYER
	L_STABLE,
#endif
#ifndef NO_JAPANESE
	L_KANA,
#endif
	L_FN,
};

enum user_code {
	CLEAR = SAFE_RANGE,
	IME,
	PRACTICE_MODE,
#ifndef NO_JAPANESE
	COMMIT_MODE,
	KANA_RANGE,
#endif
};

#ifndef NO_JAPANESE
#define BIT_NEIGHBOR_VOWEL_A BIT_VOWEL_YA
#define BIT_NEIGHBOR_VOWEL_I BIT_VOWEL_E
#define BIT_NEIGHBOR_VOWEL_U BIT_VOWEL_YU
#define BIT_NEIGHBOR_VOWEL_E BIT_VOWEL_YE
#define BIT_NEIGHBOR_VOWEL_O BIT_VOWEL_A
#define BIT_NEIGHBOR_VOWEL_YO BIT_VOWEL_U
#define BIT_NEIGHBOR_CONSONANT_A BIT_CONSONANT_N
#define BIT_NEIGHBOR_CONSONANT_K BIT_CONSONANT_R
#define BIT_NEIGHBOR_CONSONANT_S BIT_CONSONANT_T
#define BIT_NEIGHBOR_CONSONANT_T BIT_CONSONANT_P
#define BIT_NEIGHBOR_CONSONANT_H BIT_CONSONANT_A
#define BIT_NEIGHBOR_CONSONANT_R BIT_CONSONANT_M
#define BIT_CONSONANT_TH BIT_CONSONANT_R
#define BIT_NEIGHBOR_CONSONANT_TH BIT_NEIGHBOR_CONSONANT_R
#define BIT_CONSONANT_V BIT_CONSONANT_B
#endif
