SRC += process_simultaneous.c util_user.c

# BOOTMAGIC_ENABLE = no
# MOUSEKEY_ENABLE = yes
# EXTRAKEY_ENABLE = yes
# CONSOLE_ENABLE = no
COMMAND_ENABLE = no
UNICODE_ENABLE = no
SWAP_HANDS_ENABLE = no
# SLEEP_LED_ENABLE = no
# API_SYSEX_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
